//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELEASE.API.Models.dbentities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstCategory
    {
        public int ID { get; set; }
        public string Categori { get; set; }
    }
}
